import { logger } from './Logger';

export interface SecurityResult {
    isSafe: boolean;
    reason?: string;
}

export class SecurityGuard {
    // Regex-based blacklisted commands representing malicious or highly dangerous operations
    private static readonly BLACKLIST = [
        /(?:^|\s)rm\s+-[rRfFdD]*[fF]*\s+([/\\\s.*]+|(?:\.\.\/)+|~|root)/i, // rm -rf on sensitive targets, / , root, ~
        /(?:^|\s)chmod\s+(?:-R\s+)?777/i,                                  // chmod 777 (dangerous open permissions)
        /(?:^|\s)(?:curl|wget|fetch|nc|netcat|bash -i|sh -i)\b/i,          // curl/wget remote payloads & reverse shells
        /(?:^|\s)>?\s*\/dev\/sd[a-z]\b/i,                                  // Writing directly to physical storage drives
        /(?:^|\s)mkfs\b/i,                                                 // File system reformatting command
        /(?:^|\s)dd\s+if=/i,                                               // dd command (potential raw disk write)
        /(?:^|\s)mv\s+.*\s+\/dev\/null\b/i,                                // Moving files to null device (destroying them)
        /(?:^|\s)chown\s+.*(?::.*)?\s+(?:[/]|\s*root)/i                    // chown root or /
    ];

    /**
     * Inspects a command string generated by the agent against our security blacklist.
     * Blocks execution if any matching pattern of destructive mutations is found.
     */
    public static validateCommand(command: string): SecurityResult {
        const trimmedCommand = command.trim();
        logger.info(`[SecurityGuard] Auditing execution command: "${trimmedCommand}"`);

        for (const pattern of this.BLACKLIST) {
            if (pattern.test(trimmedCommand)) {
                const reason = `Security Infraction: Destructive mutation detected matching pattern ${pattern}. Execution blocked!`;
                logger.error(`[SecurityGuard] INFRACTION BLOCKED: Command "${trimmedCommand}" matched dangerous blacklist pattern.`);
                return {
                    isSafe: false,
                    reason
                };
            }
        }

        return { isSafe: true };
    }
}
